// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace DrU
{
	public partial class GameViewController : UIViewController
	{
		public GameViewController ()
		{
		}

        public override void DidReceiveMemoryWarning()
        {
            // Releases the view if it doesn't have a superview.
            base.DidReceiveMemoryWarning();

            // Release any cached data, images, etc that aren't in use.
        }


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Set the background image
            img_GameBackground.Image = UIImage.FromBundle("Default-Portrait.png");

        }


        partial void btn_GoBackMain_TouchUpInside(UIButton sender)
        {
        }
	}
}
