// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using System.Drawing;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.SpriteKit;

namespace DrU
{
	public partial class GameViewController : UIViewController
	{
		
        
         public GameViewController (IntPtr handle) : base (handle)
		{
		}
         

        public override void DidReceiveMemoryWarning()
        {
            // Releases the view if it doesn't have a superview.
            base.DidReceiveMemoryWarning();

            // Release any cached data, images, etc that aren't in use.
        }


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var q = NSUserDefaults.StandardUserDefaults.IntForKey("QuestionsAsked");
            
            var varText = new UITextField()
            {
                Frame = new RectangleF(100, 220, 200, 60),
                BackgroundColor = new UIColor(255, 255, 255, 255),
                Font = UIFont.FromName("Helvetica-Bold", 20f),
                TextAlignment = UITextAlignment.Center

            };
                       
            

            // Set the background image
           
            var background = new UIImageView
            {
                Frame = UIScreen.MainScreen.Bounds,
                Image = UIImage.FromBundle("mainbackground.jpg")
            };
            
            //adding Back button
            var btnBack = new UIButton(UIButtonType.RoundedRect)
            {
                Frame = new RectangleF(100, 100, 150, 60),
                BackgroundColor = new UIColor(160, 245, 250, 255),
                Font = UIFont.FromName("Helvetica-Bold", 30f)

            };

            varText.Text = q + " Question(s) asked";

            btnBack.SetTitle("Back", UIControlState.Normal);
            btnBack.Layer.CornerRadius = 5f;

            btnBack.TouchUpInside += (sender, args) => DismissViewController(true, null);
            View.Add(background);
            Add(btnBack);
            Add(varText);

            // end of back button
        }
 
       

        public override bool PrefersStatusBarHidden()
        {
            return true;
        }



        
	}
}
