// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Trewarren.CSMenu;

namespace DrU
{
	public partial class MenuViewController : CSMenuController
	{
		public MenuViewController (IntPtr handle) : base (handle)
		{

		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
           SetMainViewController("view_baseID");
        }


	}
}
